### ISSUE TITLE
Question about the implementation of wrapped normal

### ISSUE THREAD

**Issue by seunghyukcho** [emilemathieu/pvae#11]
Hello! My name is Seunghyuk Cho and I'm now proceeding my research based on your code.

I have a question on the implementation of wrapped normal (pvae/distributions/wrapped_normal.py).

In your paper, Algorithm 1 shows that sampling from wrapped normal distribution is proceeded as
1. sample from normal distribution
2. divide with lambda
3. apply exponential map

However, your code includes a transportation between 2) and 3). In [the original paper](http://proceedings.mlr.press/v97/nagano19a/nagano19a.pdf) that suggested wrapped normal used transportation, but your paper didn't used it and I think ignoring it make sense. So can you answer my question that using transportation is a correct implementation or it is just a mistake?

Thank you for providing the implementation of your awesome paper!

**Comment by Roy-Gao** [comment]
I have the same question as you. Besides, I'm confused about step 2. In this [paper](http://proceedings.mlr.press/v97/nagano19a/nagano19a.pdf), the author did not divide the sampled vector v by lambda. I wonder know why step 2 is necessary in poincare model, and that what the meaning of step 2 is. Thanks a lot!

**Comment by emilemathieu** [comment]
Hi both!
Sorry for the late reply.
The transport map is exactly the same thing as dividing by this lambda term (which is defined as \sqrt{|G(x)|}) in the Poincaré model :)
Hope this clarifies things.
Cheers,
emile
