### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--verify', 'HEAD']' returned non-zero exit status 128

### ISSUE THREAD

**Issue by zhp66** [emilemathieu/pvae#2]
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--verify', 'HEAD']' returned non-zero exit status 128

**Comment by Servo97** [comment]
instead of downloading the code as zip file, use git clone method.

**Comment by emilemathieu** [comment]
Sorry just saw this, I am indeed assuming that there is a git repo, this is for reproducibility purposes. Otherwise you can simply remove this git hash query line.
